### ISSUE TITLE
bug: Permite saltar al proximo jugador en turno sin tomar carta del mazo.

### ISSUE THREAD

**Issue by ernestocardenas79** [runox-game/game-engine#21]
Al no tener ninguna carta que cumpla la reglas de juego, seleccionar cualquier carta y presionar la opcion de "Jugar Carta", el juego pasa el turno al siguiente jugador siendo que deberia obligar al jugador a "Tomar una Carta" antes de pasar el turno hacia otro jugador.

**Comment by ernestocardenas79** [comment]
Expertos,  revisando  un poco creo que el detalle esta en este cambio que anexo imagen ..... cuando sucedia la situacion descrita anteriormente lanzaba el error e impedia la terminacion del turno del jugador hasta que tomara una carta del mazo.

![Captura de pantalla de 2020-08-06 21-17-23](https://user-images.githubusercontent.com/19863991/89605372-92b84f80-d82a-11ea-83f3-a979c78d7bb7.png)

**Comment by AlexScigalszky** [comment]
@ernestocardenas79 Es correcto eso. A mi parecer debe haber otra manera de mantener al jugador en el turno sin la necesidad de lanzar un Error.

A mi parecer esto soluciona el error pero necesitamos algún test (que no sé como hacerlo) para dejarlo como debe ser

```javascript
invoke(currentState: IGameState) {
    const observable = new Observable<void>((subscriber) => {
      try {
        for (let i = 0; i < this.commands.length; i++) {
          const command = this.commands[i];

          currentState.log(command.toString(), LogLevel.BEFORE_VALIDATION);
          const commandValidation = command.validate(currentState);
          if (!commandValidation.isValid) {
            currentState.log(
              `${command.toString()} invalid`,
              LogLevel.AFTER_VALIDATION,
            );
            subscriber.error(commandValidation.error);
            return;
          }
          currentState.log(
            `${command.toString()} valid`,
            LogLevel.AFTER_VALIDATION,
          );

          currentState.log(command.toString(), LogLevel.BEFORE_COMMAND);
          command.execute(currentState);
          currentState.log(command.toString(), LogLevel.BEFORE_COMMAND);
        }

        subscriber.next();
        subscriber.complete();
      } catch (error) {
        subscriber.error(error);
      }
    });

    return observable;
  }
```

¿qué opinas?

**Comment by ernestocardenas79** [comment]
**@AlexScigalszky**, si creo que ese cambio funcionaria por que a como esta en la version mas reciente creo que el return no saca del ciclo del  Array.ForEach y sigue ejecutando el siguiente comando. 

Pero al igual que tu no se como probarlo directo desde la libreria.

**Comment by jorgeucano** [comment]
Segun Facu, esta fixeado :D
