### ISSUE TITLE
Log de acciones realizadas

### ISSUE THREAD

**Issue by AlexScigalszky** [runox-game/game-engine#4]
Tener un flujo de todas acciones realizadas
Por ejemplo

1. Juan se unió
2. Pedro se unió
3. Juan arrancó la partida
4. Juan arrojó 4 Rojo
5. Pedro arrojó +4
6. Juan abandonó la partida

**Comment by facurodriguez** [comment]
Estoy de acuerdo con lo propuesto. Habría de ver la implementación porque no me gustaría que una librería externa esté logueando la consola sin control, sino que sea algo parametrizable

**Comment by AlexScigalszky** [comment]
No me refiero a un log en consola sino a un observable que pueda ver ese flujo de datos y posiblemente mostrarlos en la UI.
Yo soy de la política de no exponer cosas en el log desde una librería. 
También tendría que ser parametrizable para tener diferentes niveles porque no queremos que otro usuarios puedan ver un mensaje del tipo "Pedro intentó arrojar un 3 rojo" cuando en la mesa hay verde

**Comment by facurodriguez** [comment]
De acuerdo con todo 👏👏👏👏

**Comment by AlexScigalszky** [comment]
Genial!, estuve pensando cómo implementar algo así
Que cada Command tenga un método `log()` que es llamado por *CommandsInvoker* pero dudo que sea su responsabilidad 🤔
