### ISSUE TITLE
Eliminar código duplicado 

### ISSUE THREAD

**Issue by AlexScigalszky** [runox-game/game-engine#7]
Quitar el método duplicado `checkForPlayersWhoShouldHaveYelledUno` en las clases:
* TakeDeckCardCommand
* PlayCardCommand

**Comment by facurodriguez** [comment]
Completado en #10 

Muchas gracias @AlexScigalszky !!!!

Te recomiendo que cuando el PR es aprobado hagas un merge del master de origin en tu rama de trabajo para reducir los conflictos que se generar con cada nuevo PR.

Nuevamente, muchísimas gracias por dar una mano 😄
